export const SCREEN = {
  //authstack
  LANDING: 'LANDING',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  RESET_PASSWORD: 'RESET_PASSWORD',

  //Tabs
  ROOT: 'ROOT',
  HOME: 'HOME',
  SEARCH_BUSINESS: 'SEARCH_BUSINESS',
  FAVOURITE: 'FAVOURITE',
  NOTIFICATION: 'NOTIFICATION',
  CHAT: 'CHAT',

  //Stack-Screens
  BUSINESS_DETAILS: 'BUSINESS_DETAILS',
  THANK_YOU: 'THANK_YOU',
  SETTINGS: 'SETTINGS',

  // Settings
  PROFILE: 'PROFILE',
  CHANGED_PASSWORD: 'CHANGED_PASSWORD',
  ABOUTUS: 'ABOUTUS',
  CONTACTUS: 'CONTACTUS',


  // Chat Stack
  CHAT:'CHAT',
  CHAT_LIST:'CHAT_LIST',
  CHAT_SCREEN:'CHAT_SCREEN',
  CHAT_MEDIA:'CHAT_MEDIA'
};
