export class STATUS {
  static BOOKED = 'BOOKED';
  static CONFIRMED = 'CONFIRMED';
  static CHECKEDIN = 'CHECKEDIN';
  static CHECKED_IN = 'CHECKED_IN';
  static COMPLETED = 'COMPLETED';
  static MISSED = 'MISSED';
  static CANCELLED = 'CANCELLED';
  static PASSED = 'PASSED';
  static SERVING_NOW = 'SERVING_NOW';
  static CHECKEDIN_BY_BUSINESS = 'CHECKED_IN_BY_BUSINESS';
}
