require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'safelyq' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"





  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

    pod 'Firebase/Analytics'

    # comment the next line to disable credit card scanning
    pod 'CardIO'
    pod 'Braintree'
  
    pod 'BraintreeDropIn'
  
     # comment the next line to disable Apple pay
    pod 'Braintree/Apple-Pay'
  
     # comment the next line to disable PayPal
    pod 'Braintree/PayPal'
  
     # comment the next line to disable Venmo
    pod 'Braintree/Venmo'
  
     # Data collector for Braintree Advanced Fraud Tools
    pod 'Braintree/DataCollector'
  
    pod 'BraintreeDropIn', :inhibit_warnings => true
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    #     end
    # end

    $RNFirebaseAsStaticFramework = true
    
  target 'safelyqTests' do
    inherit! :complete
    # Pods for testing
  end

  

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end

  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
  end